# Generated by Django 5.2 on 2025-05-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_encorlabel', models.CharField(default='LabelEncoder', max_length=255)),
                ('model_file', models.CharField(max_length=255)),
                ('training_data', models.CharField(default='learnstyle_dataset.csv', max_length=255)),
                ('training_date', models.DateTimeField()),
                ('model_summary', models.TextField()),
            ],
            options={
                'db_table': 'modelinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelNada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_file', models.FileField(upload_to='models/')),
                ('training_data', models.CharField(default='course_recommendation.csv', max_length=255)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('model_summary', models.TextField()),
            ],
            options={
                'db_table': 'modelnada',
                'managed': True,
            },
        ),
    ]
