# Generated by Django 5.2 on 2025-05-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_modelinfo_modelnada"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelNajla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("model_file", models.FileField(upload_to="models/")),
                (
                    "training_data",
                    models.CharField(default="all_data_joined.csv", max_length=255),
                ),
                ("training_date", models.DateTimeField(auto_now_add=True)),
                ("model_summary", models.TextField()),
            ],
            options={
                "db_table": "modelnajla",
                "managed": True,
            },
        ),
    ]
